server:
  port: test

spring:
  application:
    name: config-center
  cloud:
    config:
      server:
        git:
          uri: asdads
          search-paths: asd
      label: master

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    prefer-ip-address: true